<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "easy_googlemap"
 *
 * Auto generated by Extension Builder 2014-06-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'EasyGoogleMap',
	'description' => 'Easy and simple Googlemap Extension for the TYPO3 CMS, Good use for company roadmap on websites and for responsive pages, based on the google maps API',
	'category' => 'misc',
	'author' => 'Andres Lobacovs, comsolit AG',
	'author_email' => 'info@comsolit.ch',
	'author_company' => 'comsolit AG',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.2.8',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0.99-7.6.99',
			'fluid' => '6.0.99-7.6.99',
			'typo3' => '6.0.99-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>